artifact_location: file:///d:/Documentos/Data/2023_CEIA/CEIA_amaq_II_project/notebook_experiments/rain_australia_model_prod/0
creation_time: 1728764165133
experiment_id: '0'
last_update_time: 1728764165133
lifecycle_stage: active
name: Default
